# Generated by Django 6.0.2 on 2026-03-02 00:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(blank=True, default='Art Collective', max_length=255),
        ),
    ]
