# Generated by Django 6.0.2 on 2026-04-06 23:33

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtWorkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AttributeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vtype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('artwork', 'Artwork')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3)),
                ('sort_by', models.CharField(default='title', help_text='title, first_published_at, or an AttributeKey name', max_length=100)),
                ('sort_dir', models.CharField(choices=[('asc', 'asc'), ('desc', 'desc')], default='asc', max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('video_embed', 2), ('external_link', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('note', 5)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('audio', 4), ('video_embed', 5), ('external_link', 8), ('statement', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to audio file'}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('file', 3), ('caption', 2)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('url', 7), ('note', 2)]], {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 2), ('body', 0)]], {})})),
                ('artists', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='works', to='collective.artistpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtworkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='collective.artwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collective.ArtworkTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ArtworkAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('val_string', models.CharField(blank=True, max_length=500)),
                ('val_number', models.FloatField(blank=True, null=True)),
                ('val_boolean', models.BooleanField(blank=True, null=True)),
                ('val_date', models.DateField(blank=True, null=True)),
                ('artwork', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='collective.artwork')),
                ('val_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='collective.artwork')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collective.attributekey')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='__tag__, __artist__, or AttributeKey name', max_length=100)),
                ('op', models.CharField(choices=[('eq', 'equals'), ('neq', 'not equals'), ('lt', 'less than'), ('gt', 'greater than'), ('contains', 'contains'), ('includes', 'includes')], default='eq', max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='collective.collection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
