# Generated by Django 6.0.2 on 2026-04-06 23:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncondition',
            name='collection',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='collective.collection'),
        ),
    ]
