# Generated by Django 6.0.2 on 2026-03-02 00:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_peopleindexpage_projectindexpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectIndexPage',
            new_name='CollectionIndexPage',
        ),
        migrations.AlterModelOptions(
            name='collectionindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peopleindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={},
        ),
        migrations.AddField(
            model_name='artpiecepage',
            name='artists',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='art_pieces', to='portfolio.personpage'),
        ),
        migrations.AlterField(
            model_name='artpiecepage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('text', 1), ('audio', 4), ('soundcloud', 5), ('embed', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to audio file'}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('audio_file', 3)]], {}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'SoundCloud URL'}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Embed code e.g. p5js, video'})}),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='people',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects', to='portfolio.personpage'),
        ),
        migrations.CreateModel(
            name='CollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('people', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='collections', to='portfolio.personpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
